// <auto-generated />
using System;
using Inventory_Managment.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory_Managment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528120000_AddInventoryApiToken")]
    partial class AddInventoryApiToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This designer file is intentionally minimal.
            // The snapshot (AppDbContextModelSnapshot.cs) is the authoritative source.
        }
    }
}
